---
- name: Install TigerVNC server
  yum:
    name: tigervnc-server
  become: true

- name: Configure GDM
  lineinfile:
    line: Enable=true
    path: /etc/gdm/custom.conf
    section: xdmcp
    option: Enable
    value: true
  become: true
  notify:
    - Restart VNC service
    - Restart GDM

- name: Start and enable VNC socket
  tags: notest
  systemd:
    enabled: true
    name: xvnc.socket
    state: started
  become: true
