---
- name: Install TigerVNC server
  yum:
    name: tigervnc-server
  become: true

- name: Configure GDM
  ini_file:
    path: /etc/gdm/custom.conf
    section: xdmcp
    option: Enable
    value: true
  become: true
  notify:
    - Restart VNC service
    - Restart GDM

- name: Configure resolution
  replace:
    path: /lib/systemd/system/xvnc@.service
    regexp: '^(ExecStart=.*geometry(?!.*?\b{{ resolution }}\b))([0-9]+x[0-9]+)(.*$)'
    replace: '\1 {{resolution}}\3'
  notify:
    - Reload systemd
    - Restart VNC Service

- name: Configure firewall
  firewalld:
    service: vnc-server
    permanent: yes
    immediate: yes
    state: enabled
  when: configure_firewall

- name: Start and enable VNC socket
  tags: notest
  systemd:
    enabled: true
    name: xvnc.socket
    state: started
  become: true
